# The Docker image that will be used to build your app
image: node:lts

cache:
  paths:
    - node_modules/
    - .next/cache

# Functions that should be executed before the build script is run
before_script:
  - yarn
pages:
  script:
    - yarn build-staging
    - rm -rf public
    - mv out public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == "staging"
